sudo: required
dist: trusty
language: node_js
node_js:
  - '7.10'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - npm config set registry http://registry.npmjs.org/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install
  - npm run build
  - npm run pree2e
  - npm start
script: 
  - npm run e2e